name: Deploy WordPress to Server

on:
  push:
    branches:
      - main # Chạy action này khi bạn push code lên nhánh main

jobs:
  web-deploy:
    name: Deploy to Server via SFTP/SSH
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      
      - name: 📂 Sync files to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}         # Phải thiết lập trong Github Secrets (VD: 116.125.141.61)
          username: ${{ secrets.SSH_USERNAME }} # Phải thiết lập trong Github Secrets (VD: root)
          password: ${{ secrets.SSH_PASSWORD }} # Phải thiết lập trong Github Secrets (VD: dE839640)
          port: 22
          
          # Chỉ định file/thư mục trên Github của bạn muốn đẩy lên
          source: "wp-content/themes/astra-child"
          
          # Thư mục gốc chứa web trên Server
          target: "/home/wp-home/"
